### ISSUE TITLE
Retrieve programming languages from Wikipedia

### ISSUE THREAD

**Issue by baudoliver7** [baudoliver7/ool-survey#1]
We want to query [Wikipedia page](https://en.wikipedia.org/wiki/List_of_programming_languages) and extract all languages mentioned.

**Comment by 0pdd** [comment]
@baudoliver7 the puzzle [#3](https://github.com/baudoliver7/ool-survey/issues/3) is still not solved.

**Comment by 0pdd** [comment]
@baudoliver7 the only puzzle [#3](https://github.com/baudoliver7/ool-survey/issues/3) is solved here.
