### ISSUE TITLE
create a csv file of languages found

### ISSUE THREAD

**Issue by baudoliver7** [baudoliver7/ool-survey#7]
We want to create a csv file with columns :
- Language
- Year            -> the year of birth
- Ver/Year     -> last version and year of release
- Kwrds         -> number of keywords
- SO              -> the popularity in StackOverflow survey
- PRs             -> the number of GitHub pull requests
- Repos.        -> the number of GitHub repository
- Scholar.      -> the number of times the language is mentioned in academics writings

**Comment by 0pdd** [comment]
@baudoliver7 3 puzzles [#10](https://github.com/baudoliver7/ool-survey/issues/10), [#11](https://github.com/baudoliver7/ool-survey/issues/11), [#9](https://github.com/baudoliver7/ool-survey/issues/9) are still not solved.

**Comment by baudoliver7** [comment]
@rultor release, tag=`0.1`

**Comment by baudoliver7** [comment]
@rultor release, tag=`0.1`
